### ISSUE TITLE
1. (Country Report) Country Populations

### ISSUE THREAD

**Issue by Karl-40443517** [Karl-40443517/coursework#5]
As an organisation we need the countries In order of largest to smallest population for the following locations:
- world
- a continent
- a region

**Comment by usmaan786** [comment]
Added the functionality to view all countries in order from largest to smallest population in the **World**.

Continents and Regions to be implemented next.

**Comment by usmaan786** [comment]
Added the functionality to view all countries in order from largest to smallest population in a specified Continent.

Regions to be implemented next.

**Comment by usmaan786** [comment]
Added the functionality to view all countries in order from largest to smallest population in a specified Region.
